### PR TITLE
Safari port

### PR DESCRIPTION
**Pull request by neon443**
I ported your extension to Safari

### CODE REVIEW

**Comment by MohammedMMC** [comment]
I don't have Safari to test it... could you provide me with a showcase video?
And have you added the new changes that i have added recently?

**Comment by neon443** [comment]
https://cloud-nia9j0jer-hack-club-bot.vercel.app/0screen_recording_2024-11-30_at_20.06.49.mp4
I added high-seas.dev to manifest, would you like me to remove Privacy Policy.md?

**Comment by MohammedMMC** [comment]
yes please, the website looks nice, but why did you remove the main website style :)

**Comment by neon443** [comment]
Removed privacy policy 
That’s just because of dark reader (different extension), not this extension

**Comment by MohammedMMC** [comment]
Sorry i can't accept it for some private reasons 😞

**Pull request closed without merging**
